version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbmarketplace
    volumes:
      - db-volume:/var/lib/postgresql/data

  api:
    image: julianaizac/marketplace
    environment:
      DB_HOST: database
    ports:
      - "9090:9090"
volumes:
  db-volume: